### ISSUE TITLE
Widget is broken on Brave

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox-widget#13]
The Firebase SDK for desktop notifications broke the widget on some browsers like Brave
![Screenshot 2023-08-17 at 12 08 16](https://github.com/WalletConnect/web3inbox-widget/assets/32299095/66ee9412-65c3-4e6f-b347-9ebf2c1dc03f)

**Comment by devceline** [comment]
Fixed in latest branch of w3i
