### ISSUE TITLE
Widget UI

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox-widget#18]
![image](https://github.com/WalletConnect/web3inbox-widget/assets/707251/473a58cb-5664-4a01-b491-509d7289136f)
![image](https://github.com/WalletConnect/web3inbox-widget/assets/707251/d51281e4-d9b8-466e-b066-8665757a0378)

The Modal should 

1. have styling as in design 
﻿https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=1989%3A90125&mode=design&t=L8aejrdGqyglmrAk-1﻿

2. close when clicking outside of the modal. Remove red "x" button.
3. be center aligned under notification icon
4. Button styles should match the design
5. Dropdown menu should match the design https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=2042%3A87736&mode=design&t=qKbllZIOgujBOQnG-1

_Originally posted by @herrhaase in https://github.com/WalletConnect/web3inbox-widget/issues/9#issuecomment-1679295503_

**Comment by devceline** [comment]
We no longer ship components with the SDK.
