### ISSUE TITLE
The modal's empty state should reflect designs ﻿

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox-widget#19]
The modal's empty state should reflect designs ﻿
![image](https://github.com/WalletConnect/web3inbox-widget/assets/707251/b02040dc-8b2e-46f4-9de8-30a275392bc8)

﻿https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=1989%3A88762&mode=design&t=L8aejrdGqyglmrAk-1

_Originally posted by @herrhaase in https://github.com/WalletConnect/web3inbox-widget/issues/9#issuecomment-1679296279_

**Comment by devceline** [comment]
We no longer have components shipped with the SDK.
