### ISSUE TITLE
Widget signature screens

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox-widget#20]
![image](https://github.com/WalletConnect/web3inbox-widget/assets/707251/78d5f33a-ef5d-4ec3-b99f-1b409541da4c)

In general, the signature screens in the modal should reflect the design as shown here https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=1989%3A86133&mode=design&t=L8aejrdGqyglmrAk-1﻿

_Originally posted by @herrhaase in https://github.com/WalletConnect/web3inbox-widget/issues/9#issuecomment-1679297226_

**Comment by devceline** [comment]
We no longer ship components with the SDK.
