### ISSUE TITLE
Notification item styles

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox-widget#21]
Text styles are not aligned with design 
<img width="316" alt="image" src="https://github.com/WalletConnect/web3inbox-widget/assets/707251/ed4af1cd-c9b9-4a94-abe2-5cb8dfb8e0eb">

How it should look
<img width="306" alt="image" src="https://github.com/WalletConnect/web3inbox-widget/assets/707251/d7507148-642b-43a2-a169-11f08bd62a50">

_Originally posted by @herrhaase in https://github.com/WalletConnect/web3inbox-widget/issues/9#issuecomment-1679329783_

<img width="432" alt="image" src="https://github.com/WalletConnect/web3inbox-widget/assets/707251/1408c83e-f183-4bea-b750-e61641250f65">

Notification card should 

1. be a row element like displayed in design https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=2042%3A87736&mode=design&t=qKbllZIOgujBOQnG-1
2. should not move on hover

_Originally posted by @herrhaase in https://github.com/WalletConnect/web3inbox-widget/issues/9#issuecomment-1679332637_

**Comment by devceline** [comment]
We no longer ship components with the SDK.
