### ISSUE TITLE
Uncaught error in iframe

### ISSUE THREAD

**Issue by chadyj** [WalletConnect/web3inbox-widget#26]
When using GM I came across an issue where the iframe died.

<img width="443" alt="Screenshot 2023-09-04 at 11 04 05" src="https://github.com/WalletConnect/web3inbox-widget/assets/116099/15272afd-cdca-40d0-bd02-6ff365320a6d">

I connected to https://notify.gm.walletconnect.com/ and attempted to subscribe.
This didn't work and there was a spinner.

I then went to the iOS wallet and subscribed directly.

Some moments later I went back to the dapp and saw the above screenshot.

On Slack it was mentioned that this can be caused by an uncaught error in iframe.

**Comment by devceline** [comment]
We no longer use iframes
