### ISSUE TITLE
Account state mismatch

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox-widget#6]
There is an issue where the widget shows the subscriptions for the previously connected account.

Steps to reproduce:
1. Connect your wallet to the widget and subscribe
2. Send 2 or 3 notifications
3. Disconnect
4. Connect with another account 
5. Open the widget and see the notifications for the previously connected account
6. [BONUS] You can even unsubscribe for the previously connected account

**Comment by devceline** [comment]
Should be fixed with https://github.com/WalletConnect/web3inbox/pull/198
