### ISSUE TITLE
A new subscription is created for each connection

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox-widget#7]
If I'm connected to the widget and I disconnect.
The second time I reconnect my wallet, the widget is asking me to subscribe again, resulting in a new subscription for the same account and dapp.

The expected behaviour is that the one and only active subscription should be shown.

**Comment by devceline** [comment]
I haven't opened gm dapp in 4 days  and reconnected and still had my subscription, tried disconnecting and reconnecting. Can you give more info on how to recreate this?

**Comment by devceline** [comment]
Fixed with new sync server updates
