### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by Cali93** [WalletConnect/web3inbox-widget#9]
- [x] Bell icon button doesn't match Figma and is missing a pointer cursor
- [x] The widget is too large on mobile screens
- [x] Close button overlaps with the widget UI
- [x] Widget z-index (should always be on top of the dapp UI)

**Comment by herrhaase** [comment]
<img width="409" alt="image" src="https://github.com/WalletConnect/web3inbox-widget/assets/707251/526907fa-b6d4-41a3-aa93-43aa5b982950">

The top separator line should sit inside the ToS sheet, instead outside of it. See designs https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=1935%3A96051&mode=design&t=qKbllZIOgujBOQnG-1

**Comment by herrhaase** [comment]
<img width="230" alt="Screenshot 2023-08-15 at 11 57 01" src="https://github.com/WalletConnect/web3inbox-widget/assets/707251/807f88c7-2c42-4700-90e9-30ef16fbe14c">

The inner corner radius of bottom ToS sheet is bigger than outer corner radius, resulting in a visible white gap.

**Comment by herrhaase** [comment]
The toggle should use these icons for active / inactive states. See designs https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=1989%3A85808&mode=design&t=L8aejrdGqyglmrAk-1

**Comment by herrhaase** [comment]
The bell icon should be replaced with this one https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=1988%3A84435&mode=design&t=L8aejrdGqyglmrAk-1

**Comment by herrhaase** [comment]
The modal's empty state should reflect designs ﻿

﻿https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=1989%3A88762&mode=design&t=L8aejrdGqyglmrAk-1

**Comment by herrhaase** [comment]
In general, the signature screens in the modal should reflect the design as shown here https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=1989%3A86133&mode=design&t=L8aejrdGqyglmrAk-1﻿

**Comment by herrhaase** [comment]
Text styles are not aligned with design 
<img width="316" alt="image" src="https://github.com/WalletConnect/web3inbox-widget/assets/707251/ed4af1cd-c9b9-4a94-abe2-5cb8dfb8e0eb">

How it should look
<img width="306" alt="image" src="https://github.com/WalletConnect/web3inbox-widget/assets/707251/d7507148-642b-43a2-a169-11f08bd62a50">

**Comment by herrhaase** [comment]
<img width="432" alt="image" src="https://github.com/WalletConnect/web3inbox-widget/assets/707251/1408c83e-f183-4bea-b750-e61641250f65">

Notification card should 

1. be a row element like displayed in design https://www.figma.com/file/P70QpTDpsgwdPJ2jJmVXxg/Web3Inbox?type=design&node-id=2042%3A87736&mode=design&t=qKbllZIOgujBOQnG-1
2. should not move on hover
